databases:
  - name: kulfi-db
    databaseName: kulfi
    user: kulfi
    plan: free

services:
  - type: web
    name: indian-kulfi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py bootstrap_inventory_data && python manage.py create_default_superuser
    startCommand: gunicorn kulfi_config.wsgi --log-file -
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kulfi-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: indian-kulfi.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://indian-kulfi.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: ADMIN_USERNAME
        value: jsdansari
      - key: ADMIN_EMAIL
        value: preseverans@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
