# Generated by Django 5.2.8 on 2026-04-02 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='movement_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The actual date of inventory movement'),
        ),
    ]
