# Generated by Django 6.0.3 on 2026-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_movement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit at the time of this movement', max_digits=10),
        ),
    ]
