# Generated by Django 6.0.3 on 2026-04-14 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_operationsexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStockTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField(default=django.utils.timezone.now)),
                ('product_key', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=200)),
                ('avg_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combined_stock', models.IntegerField(default=0)),
                ('stock_taken_count', models.IntegerField(default=0)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_stock_taken_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales Stock Taken',
                'ordering': ['-sales_date', 'product_name'],
                'unique_together': {('salesperson', 'sales_date', 'product_key')},
            },
        ),
    ]
