# Generated by Django 6.0.3 on 2026-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salesstocktaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='client_txn_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated idempotency key', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='operationsexpense',
            name='client_txn_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated idempotency key', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='client_txn_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated idempotency key', max_length=64, null=True),
        ),
    ]
