# Generated by Django 6.0.3 on 2026-04-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_client_txn_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Client-side update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='server_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operationsexpense',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Client-side update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='operationsexpense',
            name='server_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='operationsexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Client-side update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='server_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('client_txn_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entity', models.CharField(choices=[('products', 'Products'), ('inventory_movements', 'Inventory Movements'), ('sales', 'Sales'), ('expenses', 'Expenses')], max_length=40)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('duplicate', 'Duplicate'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], default='processed', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sync Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'object_id'], name='inventory_s_entity_41efcc_idx'), models.Index(fields=['user', 'client_txn_id'], name='inventory_s_user_id_c6b92b_idx')],
            },
        ),
    ]
