# Generated by Django 6.0.3 on 2026-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_operationsincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstocktaken',
            name='last_balance_count',
            field=models.IntegerField(default=0),
        ),
    ]
