# Generated by Django 6.0.3 on 2026-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_salesstocktaken_last_balance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstocktaken',
            name='balance_count',
            field=models.IntegerField(default=0),
        ),
    ]
