# Generated by Django 6.0.3 on 2026-04-22 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_salesstocktaken_balance_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('product_key', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=200)),
                ('stock_taken_count', models.IntegerField(default=0)),
                ('sales_count', models.IntegerField(default=0)),
                ('balance_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Product Reports',
                'ordering': ['-report_date', 'product_name'],
                'unique_together': {('report_date', 'salesperson', 'product_key')},
            },
        ),
    ]
