# Generated by Django 6.0.3 on 2026-04-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dailyproductreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesstocktaken',
            name='balance_count',
        ),
        migrations.RemoveField(
            model_name='salesstocktaken',
            name='last_balance_count',
        ),
        migrations.DeleteModel(
            name='DailyProductReport',
        ),
    ]
