# Generated by Django 6.0.3 on 2026-04-22 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_salesstocktaken_balance_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField(default=django.utils.timezone.now)),
                ('product_key', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=200)),
                ('balance_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_stock_balance_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales Stock Balance',
                'ordering': ['-sales_date', 'product_name'],
                'unique_together': {('salesperson', 'sales_date', 'product_key')},
            },
        ),
    ]
