# Generated by Django 6.0.3 on 2026-04-23
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_salesstockbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstockbalance',
            name='prev_balance_count',
            field=models.IntegerField(default=0, help_text="Previous day's balance count"),
        ),
    ]
