# Generated by Django 6.0.4 on 2026-04-22 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_salesstockbalance_prev_balance_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCountDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField(default=django.utils.timezone.now)),
                ('product_key', models.CharField(max_length=120)),
                ('sales_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_count_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sales_date', 'product_key'],
                'unique_together': {('salesperson', 'sales_date', 'product_key')},
            },
        ),
        migrations.DeleteModel(
            name='SalesStockBalance',
        ),
    ]
