# Generated by Django 6.0.3 on 2026-04-29 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_stockorder_stockorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='movement_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='The actual date of inventory movement'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateField(db_index=True),
        ),
    ]
