# Generated by Django 6.0.3 on 2026-05-10 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventory_movement_date_alter_sales_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='movement_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The actual date of inventory movement'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
