# Generated by Django 6.0.3 on 2026-05-05 07:40

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_expensedetailoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description or invoice number', max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('delivery_note', 'Delivery Note'), ('purchase_order', 'Purchase Order'), ('receipt', 'Receipt'), ('other', 'Other')], default='invoice', max_length=30)),
                ('supplier', models.CharField(blank=True, help_text='Supplier / Manufacturer name', max_length=200)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Date on the invoice')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total invoice amount (optional)', max_digits=12, null=True)),
                ('document', models.FileField(help_text='PDF, image, or other document file', upload_to=inventory.models.stock_invoice_upload_path)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Invoice',
                'verbose_name_plural': 'Stock Invoices',
                'ordering': ['-invoice_date', '-uploaded_at'],
            },
        ),
    ]
