# Generated by Django 6.0.3 on 2026-05-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
