# Generated by Django 6.0.3 on 2026-05-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_delete_stockinvoice'),
        ('inventory', '0020_remove_product_image'),
    ]

    operations = [
    ]
