# Generated by Django 6.0.3 on 2026-05-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_merge_20260515_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthLog',
        ),
    ]
