# Generated by Copilot on 2026-07-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_inventory_movement_date_alter_sales_sale_date'),
        ('inventory', '0022_delete_authlog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        INSERT INTO inventory_manufacturer (name, code, description, is_active, created_at, updated_at)
                        VALUES ('Indian Kulfi', 'INDIAN_KULFI', '', TRUE, NOW(), NOW())
                        ON CONFLICT (name) DO NOTHING;
                        INSERT INTO inventory_manufacturer (name, code, description, is_active, created_at, updated_at)
                        VALUES ('Kulfi Corner', 'KULFI_CORNER', '', TRUE, NOW(), NOW())
                        ON CONFLICT (name) DO NOTHING;
                        ALTER TABLE inventory_product
                        ADD COLUMN IF NOT EXISTS manufacturer_id bigint NULL;
                        DO $$
                        BEGIN
                            ALTER TABLE inventory_product
                            ADD CONSTRAINT inventory_product_manufacturer_id_fk
                            FOREIGN KEY (manufacturer_id) REFERENCES inventory_manufacturer(id) DEFERRABLE INITIALLY DEFERRED;
                        EXCEPTION
                            WHEN duplicate_object THEN NULL;
                        END $$;
                        UPDATE inventory_product
                        SET manufacturer_id = inventory_manufacturer.id
                        FROM inventory_manufacturer
                        WHERE inventory_product.manufacturer_id IS NULL
                          AND LOWER(COALESCE(inventory_product.category, '')) = LOWER(inventory_manufacturer.name);
                    """,
                    reverse_sql="""
                        ALTER TABLE inventory_product DROP CONSTRAINT IF EXISTS inventory_product_manufacturer_id_fk;
                        ALTER TABLE inventory_product DROP COLUMN IF EXISTS manufacturer_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Manufacturer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('code', models.CharField(max_length=50, unique=True)),
                        ('description', models.TextField(blank=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'ordering': ['name'],
                        'verbose_name': 'Manufacturer',
                        'verbose_name_plural': 'Manufacturers',
                    },
                ),
                migrations.AddField(
                    model_name='product',
                    name='manufacturer',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.manufacturer'),
                ),
            ],
        ),
    ]
