# Generated by Copilot on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_manufacturer'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE inventory_manufacturer
                SET name = 'Bowring', code = 'BOWRING'
                WHERE LOWER(name) = 'indian kulfi';

                UPDATE inventory_manufacturer
                SET name = 'New Bowring', code = 'NEW_BOWRING'
                WHERE LOWER(name) = 'kulfi corner';
            """,
            reverse_sql="""
                UPDATE inventory_manufacturer
                SET name = 'Indian Kulfi', code = 'INDIAN_KULFI'
                WHERE LOWER(name) = 'bowring';

                UPDATE inventory_manufacturer
                SET name = 'Kulfi Corner', code = 'KULFI_CORNER'
                WHERE LOWER(name) = 'new bowring';
            """,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('manufacturer', 'name')},
        ),
    ]
