# Generated by Copilot on 2026-07-02

from django.db import migrations, models


def rename_manufacturer_scopes(apps, schema_editor):
    Manufacturer = apps.get_model('inventory', 'Manufacturer')
    Product = apps.get_model('inventory', 'Product')

    for old_name, new_name, new_code in (
        ('Indian Kulfi', 'Bowring', 'BOWRING'),
        ('Kulfi Corner', 'New Bowring', 'NEW_BOWRING'),
    ):
        old = Manufacturer.objects.filter(name__iexact=old_name).first()
        new = Manufacturer.objects.filter(name__iexact=new_name).first()
        if not old:
            continue
        if new and new.pk != old.pk:
            Product.objects.filter(manufacturer_id=old.pk).update(manufacturer_id=new.pk)
            old.delete()
        else:
            old.name = new_name
            old.code = new_code
            old.save(update_fields=('name', 'code'))


def restore_manufacturer_scopes(apps, schema_editor):
    Manufacturer = apps.get_model('inventory', 'Manufacturer')
    Manufacturer.objects.filter(name__iexact='bowring').update(name='Indian Kulfi', code='INDIAN_KULFI')
    Manufacturer.objects.filter(name__iexact='new bowring').update(name='Kulfi Corner', code='KULFI_CORNER')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_manufacturer'),
    ]

    operations = [
        migrations.RunPython(rename_manufacturer_scopes, restore_manufacturer_scopes),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('manufacturer', 'name')},
        ),
    ]
