# Generated by Django 6.0.3 on 2026-08-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_product_manufacturer_scope'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
