# Generated by Django 6.0.3 on 2026-08-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_relax_product_name_uniqueness_and_backfill_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
