# Generated by Django 6.0.3 on 2026-08-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_stockorder_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockorder',
            old_name='customer_name',
            new_name='location',
        ),
    ]
