# Generated by Django 6.0.3 on 2026-08-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_product_unique_together'),
        ('inventory', '0027_rename_customer_name_stockorder_location'),
    ]

    operations = [
    ]
